config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  devise_for :users
  resources :users, :admin, :customer
  root 'static_pages#home'
  resources :products
  resources :orders
  resources :order_products
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
end

app/models/customer.rb
class Customer < User
  has_many :orders, dependent: :destroy
  has_many :order_products, through: :orders
  has_one :cart, dependent: :destroy
  has_many :order_products, through: :cart
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, dependent: :destroy
  has_many :order_products
  has_many :products, through: :order_products

  enum status: {
    Ordered: 0,
    Shipped: 1,
    Delivered: 2,
    Cancelled: 3
  }
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
  before_validation :normalize_name, on: :create

  validates :name, presence: true, uniqueness:  {message: "already exists!"}
  validates :price, :quantity, numericality: { only_integer: true }

  has_many :order_products, dependent: :destroy

  private
    def normalize_name
      self.name = name.downcase.titleize
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    type == 'Admin'
  end

  def customer?
    type == 'Customer'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :phone, :address, :type, :email, :password)}

       devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :phone, :address, :email, :password, :current_password)}
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def create
    @cart = Cart.new(cart_params)

    if @cart.save

    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @order_products = current_user.order_products
    # Check if query is correct or try to use current_user.order_products.
  end

  private
  def cart_params
    params.require(:cart).permit(:customer_id)
  end
# Only create & show action needed.
end

app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
  def create
    @order_product = OrderProduct.new(order_product_params)

    if @order_product.save
      flash.alert = "Added to cart successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @order_product = OrderProduct.find(params[:id])
    @order_product.delete

    redirect_to products_path, status: :see_other 
  end

  private
  def order_product_params
    params.require(:order_product).permit(:quantity, :amount)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    redirect_to orders_path, status: :see_other
  end

# Only index, show, new, create, destroy actions needed.

  private
  def order_params
    params.require(:order).permit(:status, :order_date, :total_amount)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  # GET    /products
  def index
    @products = Product.all
  end

  # GET    /products/:id
  def show
    @product = Product.find(params[:id])
  end

  # GET    /products/new
  def new
    @product = Product.new
  end

  # POST   /products
  def create 
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET    /products/:id/edit
  def edit
    @product = Product.find(params[:id])
  end

  # PUT/PATCH  /products/:id
  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /products/:id
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path, status: :see_other
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :quantity)
  end
end

# Finalized, No changes needed.

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_products_helper.rb
module OrderProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<h1>My Cart</h1>

<table class="table table-hover">
  <thead bgcolor= "#00FF7F">
    <tr>
      <th scope="col">S.No.</th>
      <th scope="col">Product Name</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Amount</th>
    </tr>
  </thead>
  <tbody>
  	<% @order_products.each do |order_product| %>
	    <tr>
	      <th scope="row">1</th>
	      <td>order_product.name</td>
	      <td>₹ order_product.price</td>
	      <td>order_product.quantity</td>
	      <td>₹ order_product.price * order_product.quantity</td>
	    </tr>
  	<% end %>
	  <tr>
	  	<td colspan="4">Total Amount:</td>
	  	<td>₹ </td>
	  </tr>
  </tbody>
</table>

app/views/order_products/index.html.erb
<h1>My Cart(OrderProducts)#index</h1>

<table class="table table-hover">
  <thead bgcolor= "#00FF7F">
    <tr>
      <th scope="col">S.No.</th>
      <th scope="col">Product Name</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Amount</th>
    </tr>
  </thead>
  <tbody>
  	<% @order_products.each do |order_product| %>
	    <tr>
	      <th scope="row">1</th>
	      <td>current_user.order_product.name</td>
	      <td>₹ current_user.order_product.price</td>
	      <td>current_user.order_product.quantity</td>
	      <td>₹ current_user.order_product.price * current_user.order_product.quantity</td>
	    </tr>
	  <% end %>
	  <tr>
	  	<td colspan="4">Total Amount:</td>
	  	<td>₹ </td>
	  </tr>
  </tbody>
</table>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>

app/views/orders/show.html.erb
<h1>Orders#show</h1>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @product.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price, min: 1 %>
    <% @product.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :quantity %><br>
    <%= form.number_field :quantity, min: 0 %>
    <% @product.errors.full_messages_for(:quantity).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1>Products List</h1>

<div class="list-group">
  <% @products.each do |product| %>
    <p class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
      <a <%= link_to product.name, product %>
      </a>
      <span class="badge badge-primary badge-pill"> ₹ <%= product.price %> </span>
    </p> 
  <% end %>
</div><br>

<% if current_user.admin? %>
  <a class="btn btn-secondary" <%= link_to "New Product", new_product_path %> </a>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p>₹<%= @product.price %></p>

<% if current_user.admin? %>
  <p><strong>Qty: </strong><%= @product.quantity %></p>

  <ul>
    <li><%= link_to "Edit", edit_product_path(@product) %></li>
    <li><%= link_to "Destroy", product_path(@product), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %></li>

  </ul>
<% else %>
  <%= form_with model: @order_product do |f| %>
    <div>
      <%= f.label :quantity, "Quantity: " %>
      <%= f.number_field :quantity, min: 1, max: @product.quantity %>
    </div><br>

    <div>
      <!-- <#%= button_to "Add to Cart", order_products_path(product_id: @product.id, cart_id: current_user.cart_id, quantity: quantity), :method => :post %> -->
    </div>
  <% end %>
<% end %>

<!-- Check if product_id, cart_id, customer_id ja rhi hai ki nhi. -->

app/views/static_pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Order Management</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>

      <% unless user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_registration_path %>">Sign Up</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_session_path %>">Log In</a>
        </li>
      <% else %>   
        <li class="nav-item">
          <a class="nav-link" href="<%= products_path %>">Products</a>
        </li>

        <% if current_user.customer? %>
          <li class="nav-item">
            <a class="nav-link" href="<%= carts_show_path %>">My Cart</a>
          </li>
        <% end %>

        <li class="nav-item">
          <a class="nav-link" href="<%= edit_user_registration_path %>">Edit Profile</a>
        </li>   

        <li class="nav-item">
          <a class="nav-link" href="<%= destroy_user_session_path %>">Log Out</a>
        </li>
      <% end %>

      <li class="nav-item">
          <a class="nav-link" href="<%= url_for(:back) %>">Back</a>
      </li>
    </ul>

    <% if user_signed_in? %>
      <form class="form-inline my-2 my-lg-0">
        <a style="color: aquamarine;"> <%= current_user.name %> (<%= current_user.type %>) </a>
      </form>
    <% end %>
  </div>
</nav>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to eStuff</h1>
</div>

app/views/users/dashboard.html.erb
<h1>Users#dashboard</h1>
<p>Find me in app/views/users/dashboard.html.erb</p>